### ISSUE TITLE
Why using static IV for CBC mode?

### ISSUE THREAD

**Issue by pergardebrink** [uservoice/uservoice-sso#4]
When looking at the C# sample (and a few others seem the same), there are some alarming issues: 

First, the IV is static which is considered a weakness for CBC mode (https://cwe.mitre.org/data/definitions/329.html), but also, the value of the IV is reverted by XOR:ing the first block with the IV making the static IV be the same as no IV? And there's also no message authentication (HMAC)?

Is this a legacy implementation for uservoice sso? The current SSO implementation seem to say you should use JWT-tokens: https://developer.uservoice.com/docs/single-sign-on/single-sign-on/

I'll see if I have time to provide a PR for JWT instead since I suspect people might end up here, implementing a less desirable sso.

**Comment by austintaylor** [comment]
@pergardebrink Yes, we are encouraging people to use JWT now. The old SSO encoding method has a number of weaknesses, as you have noted. I'm not sure if this repo is needed anymore.
